"""
streamlit_app.py — Executive Intelligence Dashboard
=====================================================
Reads from  outputs/dashboard/dashboard_payload.json
(generated by dashboard_builder.py)

Run:
    streamlit run streamlit_app.py
"""

import json
from pathlib import Path
from datetime import datetime

import streamlit as st
import plotly.graph_objects as go

# =============================================================================
# CONFIG
# =============================================================================
DASHBOARD_PAYLOAD = Path(__file__).parent / "outputs" / "dashboard" / "dashboard_payload.json"
SECTION_FILES     = Path(__file__).parent / "outputs" / "dashboard"

st.set_page_config(
    page_title="AI CEO — Strategic Intelligence Dashboard",
    page_icon="✈️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# =============================================================================
# STYLING
# =============================================================================
st.markdown("""
<style>
    /* Sidebar */
    [data-testid="stSidebar"] { background-color: #0a1628; }
    [data-testid="stSidebar"] * { color: #e0e6f0 !important; }

    /* Cards */
    .intel-card {
        background: #ffffff;
        border: 1px solid #e2e8f0;
        border-left: 4px solid #1a56db;
        border-radius: 8px;
        padding: 16px 20px;
        margin-bottom: 14px;
        box-shadow: 0 1px 4px rgba(0,0,0,0.06);
    }
    .risk-card  { border-left-color: #e53e3e; }
    .opp-card   { border-left-color: #38a169; }
    .rec-card   { border-left-color: #d69e2e; }
    .ceo-card   { border-left-color: #6b46c1; background: #faf5ff; }

    /* Badges */
    .badge {
        display: inline-block;
        padding: 2px 10px;
        border-radius: 12px;
        font-size: 0.75rem;
        font-weight: 600;
        margin-right: 6px;
        margin-bottom: 4px;
    }
    .badge-high    { background:#fee2e2; color:#991b1b; }
    .badge-medium  { background:#fef3c7; color:#92400e; }
    .badge-low     { background:#d1fae5; color:#065f46; }
    .badge-positive { background:#d1fae5; color:#065f46; }
    .badge-neutral  { background:#e5e7eb; color:#374151; }
    .badge-negative { background:#fee2e2; color:#991b1b; }
    .badge-blue    { background:#dbeafe; color:#1e40af; }
    .badge-purple  { background:#ede9fe; color:#5b21b6; }

    /* Section headings */
    .section-header {
        font-size: 1.35rem;
        font-weight: 700;
        color: #1a202c;
        border-bottom: 2px solid #1a56db;
        padding-bottom: 6px;
        margin-bottom: 20px;
    }

    /* Evidence list */
    .evidence-item::before { content: "📌 "; }
    .action-item::before   { content: "→ "; font-weight: bold; color: #6b46c1; }
</style>
""", unsafe_allow_html=True)


# =============================================================================
# DATA LOADING
# =============================================================================

@st.cache_data(ttl=60)
def load_dashboard() -> dict:
    """Load dashboard_payload.json. Returns {} if not found."""
    if DASHBOARD_PAYLOAD.exists():
        with open(DASHBOARD_PAYLOAD, encoding="utf-8") as f:
            return json.load(f)
    # Try loading individual section files
    sections = {}
    for p in sorted(SECTION_FILES.glob("section_*.json")):
        sid = p.stem
        with open(p, encoding="utf-8") as f:
            sections[sid] = json.load(f)
    if sections:
        return {"sections": sections, "built_at": "from individual files"}
    return {}


def get_section(data: dict, section_id: str) -> dict:
    return data.get("sections", {}).get(section_id, {})


def entries(section: dict) -> list:
    return section.get("entries", [])


# =============================================================================
# BADGE HELPERS
# =============================================================================

def severity_badge(level: str) -> str:
    level = (level or "").lower()
    cls   = {"high": "badge-high", "medium": "badge-medium", "low": "badge-low"}.get(level, "badge-blue")
    return f'<span class="badge {cls}">{level.upper()}</span>'


def sentiment_badge(label: str) -> str:
    label = (label or "").lower()
    cls   = {"positive": "badge-positive", "neutral": "badge-neutral", "negative": "badge-negative"}.get(label, "badge-blue")
    return f'<span class="badge {cls}">{label.upper()}</span>'


def category_badge(label: str) -> str:
    return f'<span class="badge badge-blue">{(label or "").replace("_", " ").upper()}</span>'


def priority_badge(level: str) -> str:
    return severity_badge(level)


# =============================================================================
# SECTION RENDERERS
# =============================================================================

def render_section_1(section: dict):
    st.markdown('<div class="section-header">🏢 Section 1 — Company Overview</div>', unsafe_allow_html=True)
    d = section.get("data", {})

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Company",          d.get("company_name", "—"))
    col2.metric("Industry",         d.get("industry", "—"))
    col3.metric("Collected Documents", d.get("num_collected_documents", "—"))
    col4.metric("Data Sources",     d.get("num_data_sources", "—"))

    st.markdown("---")
    c1, c2 = st.columns(2)

    with c1:
        st.markdown("**📡 Data Sources**")
        for src in d.get("data_sources", []):
            st.markdown(f"- {src}")

    with c2:
        st.markdown("**🏁 Competitors Monitored**")
        for comp in d.get("competitors_monitored", []):
            st.markdown(f"- {comp}")

    ts = d.get("last_updated", section.get("generated_at", ""))
    if ts:
        try:
            ts_fmt = datetime.fromisoformat(ts).strftime("%d %b %Y, %H:%M UTC")
        except Exception:
            ts_fmt = ts
        st.caption(f"Last updated: {ts_fmt}")


# ─────────────────────────────────────────────────────────────────────────────

def render_section_2(section: dict):
    st.markdown('<div class="section-header">📰 Section 2 — Market Intelligence</div>', unsafe_allow_html=True)

    if not entries(section):
        st.info("No market intelligence entries available yet. Run dashboard_builder.py first.")
        return

    for e in entries(section):
        if "error" in e or e.get("status") == "structuring_failed":
            st.warning(f"[{e.get('query_id')}] Structuring failed: {e.get('error','')[:200]}")
            continue

        cat_badge  = category_badge(e.get("category", ""))
        comp_badge = f'<span class="badge badge-purple">{e.get("company","")}</span>'

        st.markdown(f"""
<div class="intel-card">
  <div style="margin-bottom:8px">{cat_badge}{comp_badge}</div>
  <strong style="font-size:1.05rem">{e.get("headline","")}</strong>
  <p style="color:#4a5568;margin:8px 0">{e.get("summary","")}</p>
  <strong>Key Developments</strong>
  <ul style="margin:6px 0 0 0">
    {"".join(f"<li>{d}</li>" for d in (e.get("key_developments") or []))}
  </ul>
  <p style="color:#a0aec0;font-size:0.78rem;margin-top:8px">
    Sources: {e.get("num_sources","?")} &nbsp;|&nbsp; Date: {e.get("analysis_date","")}
  </p>
</div>
""", unsafe_allow_html=True)


# ─────────────────────────────────────────────────────────────────────────────

def render_section_3(section: dict):
    st.markdown('<div class="section-header">🚀 Section 3 — Opportunity Monitor</div>', unsafe_allow_html=True)

    if not entries(section):
        st.info("No opportunity entries available yet.")
        return

    for e in entries(section):
        if "error" in e or e.get("status") == "structuring_failed":
            st.warning(f"[{e.get('query_id')}] Structuring failed: {e.get('error','')[:200]}")
            continue

        impact  = e.get("impact_level", "")
        conf    = e.get("confidence_score", 0) or 0
        evidence = e.get("evidence") or []

        st.markdown(f"""
<div class="intel-card opp-card">
  <div style="margin-bottom:8px">
    {severity_badge(impact)}
    <span class="badge badge-blue">Confidence: {conf}%</span>
    <span class="badge badge-purple">{e.get("company","")}</span>
  </div>
  <strong style="font-size:1.05rem">{e.get("opportunity_title","")}</strong>
  <p style="color:#4a5568;margin:8px 0">{e.get("description","")}</p>
  <strong>Evidence</strong>
  <ul style="margin:6px 0 0 0">
    {"".join(f'<li class="evidence-item">{ev}</li>' for ev in evidence)}
  </ul>
  <p style="color:#a0aec0;font-size:0.78rem;margin-top:8px">Date: {e.get("analysis_date","")}</p>
</div>
""", unsafe_allow_html=True)

        # Confidence score bar
        st.progress(int(conf) / 100, text=f"Confidence: {conf}%")


# ─────────────────────────────────────────────────────────────────────────────

def render_section_4(section: dict):
    st.markdown('<div class="section-header">⚠️ Section 4 — Risk Monitor</div>', unsafe_allow_html=True)

    if not entries(section):
        st.info("No risk entries available yet.")
        return

    for e in entries(section):
        if "error" in e or e.get("status") == "structuring_failed":
            st.warning(f"[{e.get('query_id')}] Structuring failed: {e.get('error','')[:200]}")
            continue

        severity = e.get("severity_level", "")
        conf     = e.get("confidence_score", 0) or 0
        evidence = e.get("evidence") or []
        cat      = (e.get("risk_category") or "").replace("_", " ").upper()

        st.markdown(f"""
<div class="intel-card risk-card">
  <div style="margin-bottom:8px">
    {severity_badge(severity)}
    <span class="badge badge-blue">{cat}</span>
    <span class="badge badge-purple">{e.get("company","")}</span>
  </div>
  <strong style="font-size:1.05rem">{e.get("risk_title","")}</strong>
  <strong>Evidence</strong>
  <ul style="margin:6px 0 0 0">
    {"".join(f'<li class="evidence-item">{ev}</li>' for ev in evidence)}
  </ul>
  <p style="color:#a0aec0;font-size:0.78rem;margin-top:8px">
    Confidence: {conf}% &nbsp;|&nbsp; Date: {e.get("analysis_date","")}
  </p>
</div>
""", unsafe_allow_html=True)

        st.progress(int(conf) / 100, text=f"Confidence: {conf}%")


# ─────────────────────────────────────────────────────────────────────────────

def render_section_5(section: dict):
    st.markdown('<div class="section-header">💬 Section 5 — Sentiment Analysis</div>', unsafe_allow_html=True)

    if not entries(section):
        st.info("No sentiment entries available yet.")
        return

    for e in entries(section):
        if "error" in e or e.get("status") == "structuring_failed":
            st.warning(f"[{e.get('query_id')}] Structuring failed: {e.get('error','')[:200]}")
            continue

        news_label   = e.get("news_sentiment",   "neutral")
        pub_label    = e.get("public_sentiment",  "neutral")
        news_score   = float(e.get("news_sentiment_score",  0) or 0)
        pub_score    = float(e.get("public_sentiment_score", 0) or 0)
        trends       = e.get("sentiment_trends") or []
        themes       = e.get("key_themes")       or []
        summary      = e.get("sentiment_summary", "")
        company      = e.get("company", "")

        st.markdown(f'<span class="badge badge-purple">{company}</span>', unsafe_allow_html=True)
        if summary:
            st.markdown(f"> {summary}")

        # Gauge charts
        col1, col2 = st.columns(2)

        def gauge(score: float, title: str) -> go.Figure:
            # score is -1 to 1; map to 0–100 for gauge
            val = round((score + 1) / 2 * 100, 1)
            color = "#38a169" if val >= 60 else ("#d69e2e" if val >= 40 else "#e53e3e")
            fig = go.Figure(go.Indicator(
                mode="gauge+number",
                value=val,
                title={"text": title, "font": {"size": 14}},
                gauge={
                    "axis": {"range": [0, 100]},
                    "bar": {"color": color},
                    "steps": [
                        {"range": [0,  40], "color": "#fee2e2"},
                        {"range": [40, 60], "color": "#fef3c7"},
                        {"range": [60, 100], "color": "#d1fae5"},
                    ],
                    "threshold": {"line": {"color": "#1a202c", "width": 2}, "value": val},
                },
                number={"suffix": "%"},
            ))
            fig.update_layout(height=220, margin=dict(t=40, b=10, l=20, r=20))
            return fig

        with col1:
            st.plotly_chart(gauge(news_score, f"News Sentiment ({news_label.capitalize()})"),
                            use_container_width=True)
        with col2:
            st.plotly_chart(gauge(pub_score, f"Public Sentiment ({pub_label.capitalize()})"),
                            use_container_width=True)

        col3, col4 = st.columns(2)
        with col3:
            if trends:
                st.markdown("**📈 Sentiment Trends**")
                for t in trends:
                    st.markdown(f"- {t}")
        with col4:
            if themes:
                st.markdown("**🏷️ Key Themes**")
                for th in themes:
                    st.markdown(f"- {th}")

        st.markdown("---")


# ─────────────────────────────────────────────────────────────────────────────

def render_section_6(section: dict):
    st.markdown('<div class="section-header">🎯 Section 6 — Strategic Recommendations</div>', unsafe_allow_html=True)

    if not entries(section):
        st.info("No strategic recommendation entries available yet.")
        return

    for e in entries(section):
        if "error" in e or e.get("status") == "structuring_failed":
            st.warning(f"[{e.get('query_id')}] Structuring failed: {e.get('error','')[:200]}")
            continue

        priority   = e.get("priority", "")
        risk_level = e.get("risk_level", "")
        evidence   = e.get("supporting_evidence") or []
        impact     = e.get("expected_impact", "")

        st.markdown(f"""
<div class="intel-card rec-card">
  <div style="margin-bottom:8px">
    <strong>Priority:</strong> {priority_badge(priority)}
    <strong>Risk Level:</strong> {severity_badge(risk_level)}
    <span class="badge badge-purple">{e.get("company","")}</span>
  </div>
  <strong style="font-size:1.05rem">💡 {e.get("recommendation","")}</strong>
  <p style="color:#4a5568;margin:10px 0 4px 0"><strong>Expected Impact</strong></p>
  <p style="color:#4a5568;margin:0">{impact}</p>
  <p style="margin:10px 0 4px 0"><strong>Supporting Evidence</strong></p>
  <ul style="margin:0">
    {"".join(f'<li class="evidence-item">{ev}</li>' for ev in evidence)}
  </ul>
  <p style="color:#a0aec0;font-size:0.78rem;margin-top:8px">Date: {e.get("analysis_date","")}</p>
</div>
""", unsafe_allow_html=True)


# ─────────────────────────────────────────────────────────────────────────────

def render_section_7(section: dict):
    st.markdown('<div class="section-header">👔 Section 7 — CEO Briefing</div>', unsafe_allow_html=True)

    if not section or section.get("status") == "synthesis_failed":
        st.info("CEO Briefing not available yet. Run dashboard_builder.py to generate it.")
        return

    what   = section.get("what_happened", "")
    why    = section.get("why_it_matters", "")
    actions = section.get("management_actions") or []

    if what:
        st.markdown(f"""
<div class="intel-card ceo-card">
  <strong style="font-size:1rem;color:#6b46c1">🔍 What Happened?</strong>
  <p style="color:#2d3748;margin-top:8px">{what}</p>
</div>""", unsafe_allow_html=True)

    if why:
        st.markdown(f"""
<div class="intel-card ceo-card">
  <strong style="font-size:1rem;color:#6b46c1">💡 Why Does It Matter?</strong>
  <p style="color:#2d3748;margin-top:8px">{why}</p>
</div>""", unsafe_allow_html=True)

    if actions:
        items_html = "".join(
            f'<li class="action-item" style="margin-bottom:8px;color:#2d3748">{a}</li>'
            for a in actions
        )
        st.markdown(f"""
<div class="intel-card ceo-card">
  <strong style="font-size:1rem;color:#6b46c1">✅ What Should Management Do Next?</strong>
  <ol style="margin-top:10px;padding-left:20px">{items_html}</ol>
</div>""", unsafe_allow_html=True)


# =============================================================================
# SIDEBAR + MAIN LAYOUT
# =============================================================================

def main():
    data = load_dashboard()

    # ── Sidebar ──────────────────────────────────────────────────────────────
    with st.sidebar:
        st.image("https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Lufthansa_Logo_2018.svg/320px-Lufthansa_Logo_2018.svg.png",
                 width=160)
        st.markdown("## AI CEO Dashboard")
        st.markdown("Strategic Intelligence Agent")
        st.markdown("---")

        if data:
            built_at = data.get("built_at", "")
            if built_at:
                try:
                    ts = datetime.fromisoformat(built_at).strftime("%d %b %Y %H:%M")
                except Exception:
                    ts = built_at
                st.caption(f"Last built: {ts}")
        else:
            st.warning("No dashboard data found.\nRun `dashboard_builder.py` first.")

        st.markdown("---")
        nav = st.radio(
            "Navigate to",
            options=[
                "🏢 Company Overview",
                "📰 Market Intelligence",
                "🚀 Opportunity Monitor",
                "⚠️  Risk Monitor",
                "💬 Sentiment Analysis",
                "🎯 Strategic Recommendations",
                "👔 CEO Briefing",
            ],
        )

        st.markdown("---")
        if st.button("🔄 Refresh Data"):
            st.cache_data.clear()
            st.rerun()

    # ── Main content ─────────────────────────────────────────────────────────
    if not data:
        st.error("Dashboard data not found. Please run `python dashboard_builder.py` first.")
        st.code("python dashboard_builder.py")
        return

    section_map = {
        "🏢 Company Overview":          ("section_1", render_section_1),
        "📰 Market Intelligence":       ("section_2", render_section_2),
        "🚀 Opportunity Monitor":       ("section_3", render_section_3),
        "⚠️  Risk Monitor":             ("section_4", render_section_4),
        "💬 Sentiment Analysis":        ("section_5", render_section_5),
        "🎯 Strategic Recommendations": ("section_6", render_section_6),
        "👔 CEO Briefing":              ("section_7", render_section_7),
    }

    sid, renderer = section_map[nav]
    section_data  = get_section(data, sid)

    # Section 7 is a flat dict, not a section wrapper
    if sid == "section_7":
        renderer(section_data)
    else:
        status = section_data.get("status", "")
        if status == "partial":
            skipped = section_data.get("skipped_ids", [])
            st.warning(f"Partial data — {len(skipped)} query file(s) not yet available: {skipped}")
        renderer(section_data)


if __name__ == "__main__":
    main()
